<a href="https://colab.research.google.com/github/mohansaidinesh/Machine-Learning/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Diabetes Prediction Classifier using Logistic Regression.**

Import Packages, Functions and classes


In [428]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [429]:
data=pd.read_csv("https://assets.datacamp.com/production/repositories/628/datasets/444cdbf175d5fbf564b564bd36ac21740627a834/diabetes.csv")
data.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [430]:
X = data.drop('diabetes', axis=1).values
y = data['diabetes'].values

In [431]:
X[0], y[0]

(array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ]), 1)

In [432]:
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.2, random_state=0)

In [433]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([  7.   , 150.   ,  78.   ,  29.   , 126.   ,  35.2  ,   0.692,
         54.   ]), 59.9865, 50.89017268343663)

In [434]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [435]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([0.90832902, 0.91569367, 0.44912368, 0.52222619, 0.3736349 ,
        0.37852648, 0.67740401, 1.69955804]),
 0.7405620009571598,
 0.41545024515724205)

In [436]:
model = LogisticRegression(C=0.09,multi_class='ovr',random_state=0)
model.fit(X_train, y_train)

LogisticRegression(C=0.09, multi_class='ovr', random_state=0)

In [437]:
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

In [438]:
model.score(X_train, y_train)

0.757328990228013

In [439]:
model.score(X_test, y_test)


0.8246753246753247

In [440]:
confusion_matrix(y_test, y_pred)

array([[98,  9],
       [18, 29]])

In [441]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88       107
           1       0.76      0.62      0.68        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154

